/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import Models.Conexion;
import java.awt.Color;
import java.sql.*;
/**
 *
 * @author josepa
 */
public class perfil extends javax.swing.JFrame {
    int xmouse, ymouse;
    Conexion cn = new Conexion();
    public perfil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonsalir = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        realizarventa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        realizarcompra = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        empresa = new javax.swing.JLabel();
        minilogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(820, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonsalir.setBackground(new java.awt.Color(78, 78, 78));

        salir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonsalirLayout = new javax.swing.GroupLayout(botonsalir);
        botonsalir.setLayout(botonsalirLayout);
        botonsalirLayout.setHorizontalGroup(
            botonsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonsalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonsalirLayout.setVerticalGroup(
            botonsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonsalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 80, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        jPanel2.setBackground(new java.awt.Color(251, 198, 138));

        realizarventa.setBackground(new java.awt.Color(247, 142, 30));
        realizarventa.setFont(new java.awt.Font("Alumni Sans Pinstripe", 1, 48)); // NOI18N
        realizarventa.setForeground(new java.awt.Color(255, 255, 255));
        realizarventa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        realizarventa.setText("REALIZAR VENTA");
        realizarventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                realizarventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                realizarventaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(realizarventa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(realizarventa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 350, 130));

        jPanel3.setBackground(new java.awt.Color(179, 179, 179));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        realizarcompra.setBackground(new java.awt.Color(232, 232, 232));
        realizarcompra.setFont(new java.awt.Font("Alumni Sans Pinstripe", 1, 48)); // NOI18N
        realizarcompra.setForeground(new java.awt.Color(255, 255, 255));
        realizarcompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        realizarcompra.setText("REALIZAR COMPRA");
        realizarcompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarcompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                realizarcompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                realizarcompraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(realizarcompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(realizarcompra, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 350, 130));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/250px-Simple_cardboard_box.svg.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 250, 170));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.jpg"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fondo.setName("imagen1"); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 250, 470));

        empresa.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empresa.setText("BOXCLOUD");
        jPanel1.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 250, -1));

        minilogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/box-solid-24.png"))); // NOI18N
        jPanel1.add(minilogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        cn.desconectar();
        login entrar = new login();
        entrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        botonsalir.setBackground(new Color(232,232,232));
        salir.setForeground(Color.black);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        botonsalir.setBackground(new Color(78,78,78));
        salir.setForeground(Color.white);
    }//GEN-LAST:event_salirMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xmouse = evt.getX();
        ymouse= evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_headerMouseDragged

    private void realizarcompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarcompraMouseEntered
        jPanel3.setBackground(new Color(78,78,78));
        realizarcompra.setForeground(new Color(247,142,30));
    }//GEN-LAST:event_realizarcompraMouseEntered

    private void realizarcompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarcompraMouseExited
        jPanel3.setBackground(new Color(179,179,179));
        realizarcompra.setForeground(Color.white);
    }//GEN-LAST:event_realizarcompraMouseExited

    private void realizarventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarventaMouseEntered
        jPanel2.setBackground(new Color(247,142,30));
        realizarventa.setForeground(Color.black);
    }//GEN-LAST:event_realizarventaMouseEntered

    private void realizarventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarventaMouseExited
        jPanel2.setBackground(new Color(251,198,138));
        realizarventa.setForeground(Color.white);
    }//GEN-LAST:event_realizarventaMouseExited

    private void realizarcompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarcompraMouseClicked
        compra();
    }//GEN-LAST:event_realizarcompraMouseClicked

    public void compra(){
        PanelAdmin perfilcompra = new PanelAdmin();
        perfilcompra.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonsalir;
    private javax.swing.JLabel empresa;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minilogo;
    private javax.swing.JLabel realizarcompra;
    private javax.swing.JLabel realizarventa;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
